version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdbname
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=yourpassword
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: